/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xyz.thrift.datatype;


@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class thrift_datatypeConstants {

  public static final String VERSION = "1.2.1";

}
